### ISSUE TITLE
Problems using yahoo.finance.stock

### ISSUE THREAD

**Issue by anoopjohn** [tpowers/yql-tables#1]
Hi,

I tried use env=http://github.com/tpowers/yql-tables/raw/adf58b56a19837099c13ef1b07d55b08f0f30b0a/yahoo/finance/yahoo.finance.stock.xml

and run a query at http://developer.yahoo.com/yql/console/
But I keep getting errors "no viable alternative at character" for ? { [ etc.

Can you please point me as to how to use this.

Thanks
Anoop

**Comment by tpowers** [comment]
It looks like yahoo just fixed the use of raw github xml files in the YQL Console.

So you can now just do this:
    use "http://github.com/tpowers/yql-tables/raw/adf58b56a19837099c13ef1b07d55b08f0f30b0a/yahoo/finance/yahoo.finance.stock.xml" as stock;
    select \* from stock where symbol="yhoo";

See [Example Queries](http://wiki.github.com/tpowers/yql-tables/example-queries) for more examples.

**Comment by anoopjohn** [comment]
Thanks for the reply. It is working perfectly fine now. Thanks for the other replies too :-)

Cheers
Anoop
